### PR TITLE
Add more symbols for branch, has_untracked_files, has_pending_commits, etc

### PR DESCRIPTION
**Pull request by yc2prime**
Add symbols for branch, has_untracked_files, has_pending_commits and clean

### CODE REVIEW

**Comment by dserodio** [comment]
Nice

**Comment by GonZo** [comment]
Very nice :+1:

**Comment by mcdope** [comment]
does this need a special font?

asking cuz i cherry-picked this but it doesn't show for me...

**Comment by b-ryan** [comment]
Looks pretty nice. My biggest hesitation with this change is that the symbol for clean vs. dirty seems superfluous. The background color already captures that.

**Comment by caseyfw** [comment]
I agree, what makes powerline-shell different from the numerous other "pretty shells" out there is the lack of clutter.

**Comment by b-ryan** [comment]
#136 add some functionality similar to this so I'm going to close this issue. While the icon for the branch is nice, I don't think it adds any information so I'm still hesitant to add.

**Pull request closed without merging**
