### PR TITLE
git: added untracked changes icon

### PR DESCRIPTION
**Pull request by Zolmeister**

### CODE REVIEW

**Comment by b-ryan** [comment]
Hi @Zolmeister, thanks for contributing. I am worried about having too many symbols where people have a hard time understanding what they mean, so I'm hesitant to add any. What was the problem you were running into where this helped?

**Comment by Zolmeister** [comment]
My process goes like this.
  1. Edit files
  2. commit and push via `git commit -am'messege'` && git push (note the `-a`)

Limiting terminal feedback to only new files or unpushed changes means that pending changes are left out.

**Comment by ryanoasis** [comment]
Maybe if this was made optional?

**Comment by b-ryan** [comment]
Am I understanding you correctly that the issue is distinguishing between when you have untracked files versus pending changes?

If so, this is something I have been thinking about. I personally do not like that the prompt is red when I only have untracked files. The `+` already shows when I have untracked files. I would like it if red only indicated pending changes. Then we would not need a separate symbol to indicate pending changes.

Would this be an acceptable solution? The biggest issue with this approach would be potentially breaking people's workflows. I am not sure how to tell how many people rely on red the way it is currently implemented.

**Comment by Zolmeister** [comment]
@b-ryan Personally I find the color change too distracting and thus prefer the symbol. It's fine if you don't want to merge, I understand it adds quite a bit and affects many users, I'm happy to maintain my own fork.

**Comment by b-ryan** [comment]
The git segment just got a bunch of changes via #136. They create conflicts with this branch. But more importantly, I think they cover what you are going for. So I'm going to close but feel free to open a new pull request if you think `git` could be further improved.

**Pull request closed without merging**
